package com.example.madhu_siri.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.compositionLocalOf

enum class TextKey {
    APP_NAME,
    ROLE_FARMER,
    ROLE_BEEKEEPER,
    NAV_DASHBOARD,
    NAV_MAP,
    NAV_SPRAY,
    NAV_TIPS,
    TITLE_HIVE_MAP,
    TITLE_SPRAY_ALERT,
    TITLE_PROFILE,
    TITLE_BEE_FRIENDLY_TIPS,
    TITLE_BEEKEEPER_DASHBOARD,
    TITLE_FARMER_DASHBOARD,
    LOGIN_SUBTITLE,
    LOGIN_TITLE,
    LOGIN_ROLE_HELP,
    EMAIL,
    PASSWORD,
    GOOGLE_SIGN_IN,
    CONTINUE_AS,
    CREATE_NEW_ACCOUNT,
    REGISTER_TITLE,
    REGISTER_SUBTITLE,
    FULL_NAME,
    PHONE_NUMBER,
    CONFIRM_PASSWORD,
    APP_LANGUAGE,
    CREATE_ACCOUNT_AS,
    BACK_TO_LOGIN,
    PROFILE_USER_INFO,
    PROFILE_ACCOUNT_ACTIONS,
    PROFILE_DISPLAY_HELP,
    PROFILE_THEME,
    PROFILE_SAVE,
    PROFILE_NOTIFICATION_HISTORY,
    PROFILE_SPRAY_HISTORY,
    PROFILE_HEALTH_LOGS,
    PROFILE_SWITCH_TO,
    PROFILE_SWITCH_ACCOUNT,
    PROFILE_LOG_OUT,
    THEME_SYSTEM,
    THEME_LIGHT,
    THEME_DARK,
    MAP_SUMMARY_BEEKEEPER,
    MAP_SUMMARY_FARMER,
    MAP_GUIDE_BEEKEEPER,
    MAP_GUIDE_FARMER,
    MAP_HIVE_COUNT,
    MAP_SPRAY_COUNT,
    MAP_BEES_ACTIVE,
    MAP_BEEKEEPER_CONTACT,
    MAP_PROTECTED_HIVE,
    MAP_NEW_HIVE_PIN,
    MAP_UPDATED_HIVE_PIN,
    MAP_SAVE_HIVE_PIN,
    MAP_EDIT_HIVE,
    MAP_MOVE_PIN,
    MAP_SAVE,
    MAP_CANCEL,
    MAP_NOTES,
    MAP_HIVE_NAME,
    MAP_SPRAY_ALERT,
    SPRAY_CONTROL_TITLE,
    SPRAY_CONTROL_SUBTITLE,
    SPRAY_TIMING_TYPE,
    SPRAY_POINT_SELECTION,
    SPRAY_USE_CURRENT_LOCATION,
    SPRAY_CLEAR_PIN,
    SPRAY_TYPE,
    CHEMICAL_NAME,
    SPRAY_DURATION,
    SPRAY_DURATION_HELP,
    SPRAY_START_IN_MINUTES,
    FARMER_NOTE,
    SPRAY_SELECTED_POINT,
    SPRAY_TAP_MAP_HELP,
    SPRAY_ACTION,
    ALERT_START,
    NEARBY_HIVES,
    NO_HIVE_PINS,
    NO_HIVE_PINS_HELP,
    HIVE_TRACKER,
    ACTIVE_ALERTS_NEAR_HIVES,
    NO_ALERTS,
    NO_ALERTS_HELP,
    FARMER_FIELD_READINESS,
    FARMER_FIELD_READINESS_HELP,
    SPRAY_HISTORY,
    NO_SPRAY_HISTORY,
    NO_SPRAY_HISTORY_HELP,
    BEEKEEPER_DASHBOARD_SUBTITLE,
    FARMER_DASHBOARD_SUBTITLE,
    RECENT_TRACKER_ENTRIES,
    NO_LOGS,
    NO_LOGS_HELP,
    TIPS_TITLE,
    TIPS_SUBTITLE,
    TIP_1_TITLE,
    TIP_1_BODY,
    TIP_2_TITLE,
    TIP_2_BODY,
    TIP_3_TITLE,
    TIP_3_BODY,
    TIP_4_TITLE,
    TIP_4_BODY,
    TIP_5_TITLE,
    TIP_5_BODY
}

@Immutable
class AppText(private val values: Map<TextKey, String>) {
    operator fun invoke(key: TextKey, vararg args: Any): String {
        val template = values[key] ?: englishStrings[key].orEmpty()
        return if (args.isEmpty()) template else String.format(template, *args)
    }
}

val LocalAppText = compositionLocalOf { AppText(englishStrings) }

@Composable
fun ProvideAppText(language: AppLanguage, content: @Composable () -> Unit) {
    val values = when (language) {
        AppLanguage.ENGLISH -> englishStrings
        AppLanguage.KANNADA -> kannadaStrings
        AppLanguage.HINDI -> hindiStrings
        AppLanguage.TELUGU -> teluguStrings
        AppLanguage.TAMIL -> tamilStrings
    }
    CompositionLocalProvider(LocalAppText provides AppText(values), content = content)
}

private val englishStrings = mapOf(
    TextKey.APP_NAME to "Madhu-Siri",
    TextKey.ROLE_FARMER to "Farmer",
    TextKey.ROLE_BEEKEEPER to "Beekeeper",
    TextKey.NAV_DASHBOARD to "Dashboard",
    TextKey.NAV_MAP to "Map",
    TextKey.NAV_SPRAY to "Spray",
    TextKey.NAV_TIPS to "Tips",
    TextKey.TITLE_HIVE_MAP to "Hive Map",
    TextKey.TITLE_SPRAY_ALERT to "Spray Alert",
    TextKey.TITLE_PROFILE to "Profile",
    TextKey.TITLE_BEE_FRIENDLY_TIPS to "Bee-Friendly Tips",
    TextKey.TITLE_BEEKEEPER_DASHBOARD to "Beekeeper Dashboard",
    TextKey.TITLE_FARMER_DASHBOARD to "Farmer Dashboard",
    TextKey.LOGIN_SUBTITLE to "Bee-farmer harmony before every spray.",
    TextKey.LOGIN_TITLE to "Sign in",
    TextKey.LOGIN_ROLE_HELP to "Choose the role you want to enter with this account.",
    TextKey.EMAIL to "Email",
    TextKey.PASSWORD to "Password",
    TextKey.GOOGLE_SIGN_IN to "Continue with Google",
    TextKey.CONTINUE_AS to "Continue as %s",
    TextKey.CREATE_NEW_ACCOUNT to "Create a new account",
    TextKey.REGISTER_TITLE to "Create account",
    TextKey.REGISTER_SUBTITLE to "Choose your role and language so the app opens the right experience immediately.",
    TextKey.FULL_NAME to "Full name",
    TextKey.PHONE_NUMBER to "Contact number",
    TextKey.CONFIRM_PASSWORD to "Confirm password",
    TextKey.APP_LANGUAGE to "App language",
    TextKey.CREATE_ACCOUNT_AS to "Create %s account",
    TextKey.BACK_TO_LOGIN to "Back to login",
    TextKey.PROFILE_USER_INFO to "User info",
    TextKey.PROFILE_ACCOUNT_ACTIONS to "Account actions",
    TextKey.PROFILE_DISPLAY_HELP to "Update your contact details, app language, and theme here.",
    TextKey.PROFILE_THEME to "Theme",
    TextKey.PROFILE_SAVE to "Save profile settings",
    TextKey.PROFILE_NOTIFICATION_HISTORY to "Notification history",
    TextKey.PROFILE_SPRAY_HISTORY to "Spray history",
    TextKey.PROFILE_HEALTH_LOGS to "Health and honey logs",
    TextKey.PROFILE_SWITCH_TO to "Switch to %s mode",
    TextKey.PROFILE_SWITCH_ACCOUNT to "Switch account",
    TextKey.PROFILE_LOG_OUT to "Log out",
    TextKey.THEME_SYSTEM to "System",
    TextKey.THEME_LIGHT to "Light",
    TextKey.THEME_DARK to "Dark",
    TextKey.MAP_SUMMARY_BEEKEEPER to "Your live hive map",
    TextKey.MAP_SUMMARY_FARMER to "Nearby hive and spray view",
    TextKey.MAP_GUIDE_BEEKEEPER to "Tap a hive pin to review contact details, update bee-out times, or move the location.",
    TextKey.MAP_GUIDE_FARMER to "Check hive pins first. If bees are due out soon, wait for the safe spray window shown in Spray Alert.",
    TextKey.MAP_HIVE_COUNT to "%d hive pins",
    TextKey.MAP_SPRAY_COUNT to "%d live spray zones",
    TextKey.MAP_BEES_ACTIVE to "Bees go out: %s - %s",
    TextKey.MAP_BEEKEEPER_CONTACT to "Beekeeper contact: %s",
    TextKey.MAP_PROTECTED_HIVE to "Protected beekeeper hive",
    TextKey.MAP_NEW_HIVE_PIN to "New hive pin",
    TextKey.MAP_UPDATED_HIVE_PIN to "Updated hive pin",
    TextKey.MAP_SAVE_HIVE_PIN to "Save hive pin",
    TextKey.MAP_EDIT_HIVE to "Edit hive",
    TextKey.MAP_MOVE_PIN to "Move this pin on the map",
    TextKey.MAP_SAVE to "Save",
    TextKey.MAP_CANCEL to "Cancel",
    TextKey.MAP_NOTES to "Notes",
    TextKey.MAP_HIVE_NAME to "Hive name",
    TextKey.MAP_SPRAY_ALERT to "Spray alert",
    TextKey.SPRAY_CONTROL_TITLE to "Spray alert control",
    TextKey.SPRAY_CONTROL_SUBTITLE to "Share the planned spray time early so nearby beekeepers can keep bees safely inside.",
    TextKey.SPRAY_TIMING_TYPE to "Spray timing and type",
    TextKey.SPRAY_POINT_SELECTION to "Spray point selection",
    TextKey.SPRAY_USE_CURRENT_LOCATION to "Use current location",
    TextKey.SPRAY_CLEAR_PIN to "Clear pin",
    TextKey.SPRAY_TYPE to "Spray type",
    TextKey.CHEMICAL_NAME to "Chemical name",
    TextKey.SPRAY_DURATION to "Planned spray duration (hours)",
    TextKey.SPRAY_DURATION_HELP to "Please try to spray at least 4 hours before any nearby hive opens, so bees can stay protected.",
    TextKey.SPRAY_START_IN_MINUTES to "Starts in how many minutes?",
    TextKey.FARMER_NOTE to "Message for nearby beekeepers",
    TextKey.SPRAY_SELECTED_POINT to "Selected spray point: %.5f, %.5f",
    TextKey.SPRAY_TAP_MAP_HELP to "Tap the map or use current location to mark the field.",
    TextKey.SPRAY_ACTION to "Send spray alert",
    TextKey.ALERT_START to "Alert start: %s",
    TextKey.NEARBY_HIVES to "Nearby village hives",
    TextKey.NO_HIVE_PINS to "No hive pins available",
    TextKey.NO_HIVE_PINS_HELP to "Beekeeper hive pins will appear here in real time as they are added.",
    TextKey.HIVE_TRACKER to "Hive tracker",
    TextKey.ACTIVE_ALERTS_NEAR_HIVES to "Active alerts near your hives",
    TextKey.NO_ALERTS to "No active spray alerts nearby",
    TextKey.NO_ALERTS_HELP to "When a farmer schedules a spray within 2 km of your hive pins, it will appear here.",
    TextKey.FARMER_FIELD_READINESS to "Field readiness",
    TextKey.FARMER_FIELD_READINESS_HELP to "Open Spray Alert to choose a field, check hive safety, and send one clear alert to nearby beekeepers.",
    TextKey.SPRAY_HISTORY to "Spray history",
    TextKey.NO_SPRAY_HISTORY to "No spray events yet",
    TextKey.NO_SPRAY_HISTORY_HELP to "Your spray history will appear here after the first alert is submitted.",
    TextKey.BEEKEEPER_DASHBOARD_SUBTITLE to "Monitor hives, review nearby spray alerts, and keep honey and health records in one place.",
    TextKey.FARMER_DASHBOARD_SUBTITLE to "Plan safer spray windows and avoid conflicts with nearby hive release timings.",
    TextKey.RECENT_TRACKER_ENTRIES to "Recent tracker entries",
    TextKey.NO_LOGS to "No logs yet",
    TextKey.NO_LOGS_HELP to "Health checks and honey production entries will appear here newest first.",
    TextKey.TIPS_TITLE to "Safety tips",
    TextKey.TIPS_SUBTITLE to "Short reminders for bee-safe spraying and healthy hive coordination.",
    TextKey.TIP_1_TITLE to "Spray after foraging hours",
    TextKey.TIP_1_BODY to "Evening or night spraying lowers the chance of direct bee contact during active pollination.",
    TextKey.TIP_2_TITLE to "Watch wind drift",
    TextKey.TIP_2_BODY to "Strong wind can carry chemicals past the target field and into hive foraging paths.",
    TextKey.TIP_3_TITLE to "Prefer bee-safer products",
    TextKey.TIP_3_BODY to "Use the least harmful option that still works for the crop and follow label directions closely.",
    TextKey.TIP_4_TITLE to "Notify before spraying",
    TextKey.TIP_4_BODY to "Use Madhu-Siri before spraying so beekeepers can close hives, protect water, and plan safely.",
    TextKey.TIP_5_TITLE to "Remember flowering edges",
    TextKey.TIP_5_BODY to "Bees visit wildflowers and flowering weeds even when the crop itself is not in bloom."
)

private fun translated(base: Map<TextKey, String>, overrides: Map<TextKey, String>) = base + overrides

private val kannadaStrings = translated(
    englishStrings,
    mapOf(
        TextKey.NAV_DASHBOARD to "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        TextKey.NAV_MAP to "ನಕ್ಷೆ",
        TextKey.NAV_SPRAY to "ಸಿಂಪಡಣೆ",
        TextKey.NAV_TIPS to "ಸಲಹೆಗಳು",
        TextKey.TITLE_PROFILE to "ಪ್ರೊಫೈಲ್",
        TextKey.THEME_SYSTEM to "ಸಿಸ್ಟಮ್",
        TextKey.THEME_LIGHT to "ಲೈಟ್",
        TextKey.THEME_DARK to "ಡಾರ್ಕ್",
        TextKey.APP_LANGUAGE to "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
        TextKey.SPRAY_ACTION to "ಸಿಂಪಡಣೆ ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ",
        TextKey.SPRAY_USE_CURRENT_LOCATION to "ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ",
        TextKey.PROFILE_SAVE to "ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ",
        TextKey.PROFILE_LOG_OUT to "ಲಾಗ್ ಔಟ್"
    )
)

private val hindiStrings = translated(
    englishStrings,
    mapOf(
        TextKey.NAV_DASHBOARD to "डैशबोर्ड",
        TextKey.NAV_MAP to "मानचित्र",
        TextKey.NAV_SPRAY to "छिड़काव",
        TextKey.NAV_TIPS to "सुझाव",
        TextKey.TITLE_PROFILE to "प्रोफाइल",
        TextKey.THEME_SYSTEM to "सिस्टम",
        TextKey.THEME_LIGHT to "लाइट",
        TextKey.THEME_DARK to "डार्क",
        TextKey.APP_LANGUAGE to "ऐप भाषा",
        TextKey.SPRAY_ACTION to "छिड़काव अलर्ट भेजें",
        TextKey.SPRAY_USE_CURRENT_LOCATION to "वर्तमान स्थान उपयोग करें",
        TextKey.PROFILE_SAVE to "प्रोफाइल सेटिंग्स सहेजें",
        TextKey.PROFILE_LOG_OUT to "लॉग आउट"
    )
)

private val teluguStrings = translated(
    englishStrings,
    mapOf(
        TextKey.NAV_DASHBOARD to "డ్యాష్‌బోర్డ్",
        TextKey.NAV_MAP to "మ్యాప్",
        TextKey.NAV_SPRAY to "స్ప్రే",
        TextKey.NAV_TIPS to "సూచనలు",
        TextKey.TITLE_PROFILE to "ప్రొఫైల్",
        TextKey.THEME_SYSTEM to "సిస్టమ్",
        TextKey.THEME_LIGHT to "లైట్",
        TextKey.THEME_DARK to "డార్క్",
        TextKey.APP_LANGUAGE to "యాప్ భాష",
        TextKey.SPRAY_ACTION to "స్ప్రే అలర్ట్ పంపండి",
        TextKey.SPRAY_USE_CURRENT_LOCATION to "ప్రస్తుత స్థానం వాడండి",
        TextKey.PROFILE_SAVE to "ప్రొఫైల్ సెట్టింగ్స్ సేవ్ చేయండి",
        TextKey.PROFILE_LOG_OUT to "లాగ్ అవుట్"
    )
)

private val tamilStrings = translated(
    englishStrings,
    mapOf(
        TextKey.NAV_DASHBOARD to "டாஷ்போர்டு",
        TextKey.NAV_MAP to "வரைபடம்",
        TextKey.NAV_SPRAY to "தெளிப்பு",
        TextKey.NAV_TIPS to "குறிப்புகள்",
        TextKey.TITLE_PROFILE to "சுயவிவரம்",
        TextKey.THEME_SYSTEM to "சிஸ்டம்",
        TextKey.THEME_LIGHT to "ஒளி",
        TextKey.THEME_DARK to "இருள்",
        TextKey.APP_LANGUAGE to "அப்பின் மொழி",
        TextKey.SPRAY_ACTION to "தெளிப்பு எச்சரிக்கை அனுப்பு",
        TextKey.SPRAY_USE_CURRENT_LOCATION to "தற்போதைய இடம் பயன்படுத்து",
        TextKey.PROFILE_SAVE to "சுயவிவர அமைப்புகளை சேமிக்கவும்",
        TextKey.PROFILE_LOG_OUT to "வெளியேறு"
    )
)
